-- ============================

-- Ce fichier a été créé à l'aide de l'utilitaire dblook de Derby.
-- Horodatage : 2018-06-08 01:17:53.601
-- La base de données source est : /Users/camilledesmots/.netbeans-derby/GeigerCounter
-- L'URL de connexion est : jdbc:derby://localhost:1527//Users/camilledesmots/.netbeans-derby/GeigerCounter;user=GeigerCounter;password=GeigerCounter
-- appendLogs: false

-- ----------------------------------------------
-- Instructions DDL pour les schémas
-- ----------------------------------------------

CREATE SCHEMA "DATA";

CREATE SCHEMA "GEIGERCOUNTER";

-- ----------------------------------------------
-- Instructions DDL pour les tables
-- ----------------------------------------------

CREATE TABLE "DATA"."HARDWARE" ("HARDWAREID" SMALLINT NOT NULL, "VERSION" VARCHAR(14), "SERIALNUMBER" VARCHAR(25));

CREATE TABLE "GEIGERCOUNTER"."TEST" ("ID" INTEGER NOT NULL, "COL1" CHAR(1));

CREATE TABLE "DATA"."CPM" ("HARWAREID" SMALLINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "TIMESTAMP" TIMESTAMP NOT NULL, "CPM" INTEGER);

CREATE TABLE "GEIGERCOUNTER"."HARDWARE" ("HARDWAREID" SMALLINT NOT NULL, "SERIALNUMBER" VARCHAR(255), "VERSION" VARCHAR(255));

CREATE TABLE "GEIGERCOUNTER"."CPM" ("CPM" INTEGER, "HARDWAREID" SMALLINT NOT NULL, "TIMESTAMP" TIMESTAMP NOT NULL);

CREATE TABLE "GEIGERCOUNTER"."SEQUENCE" ("SEQ_NAME" VARCHAR(50) NOT NULL, "SEQ_COUNT" DECIMAL(15,0));

CREATE TABLE "DATA"."TEST" ("ID" INTEGER NOT NULL, "COL1" CHAR(1));

-- ----------------------------------------------
-- Instructions DDL pour les clés
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "DATA"."HARDWARE" ADD CONSTRAINT "SQL171207143314930" PRIMARY KEY ("HARDWAREID");

ALTER TABLE "GEIGERCOUNTER"."SEQUENCE" ADD CONSTRAINT "SQL180520152311770" PRIMARY KEY ("SEQ_NAME");

ALTER TABLE "GEIGERCOUNTER"."TEST" ADD CONSTRAINT "SQL180520172312510" PRIMARY KEY ("ID");

ALTER TABLE "DATA"."CPM" ADD CONSTRAINT "SQL171207143932130" PRIMARY KEY ("HARWAREID", "TIMESTAMP");

ALTER TABLE "DATA"."TEST" ADD CONSTRAINT "SQL180520170727330" PRIMARY KEY ("ID");

ALTER TABLE "GEIGERCOUNTER"."CPM" ADD CONSTRAINT "SQL180603215057420" PRIMARY KEY ("HARDWAREID", "TIMESTAMP");

ALTER TABLE "GEIGERCOUNTER"."HARDWARE" ADD CONSTRAINT "SQL180520152311750" PRIMARY KEY ("HARDWAREID");

